// generated types (supabase)
export type Course = {
  id: string;
  title: string;
  subtitle: string | null;
  description: string | null;
  level: string | null;
  language: string | null;
  thumbnail_url: string | null;
  intro_video_url: string | null;
  price_cents: number;
  currency: string;
  is_published: boolean;
  status: string | null;
  instructor_id: string;
  created_at: string;
  updated_at: string;
  prerequisites: string | null;
  estimated_duration_hours: number | null;
  learning_outcomes: string[] | null;
  target_audience: string | null;
  requirements: string | null;
  allow_in_bundles: boolean | null;
  bundle_discount_percent: number | null;
  enable_qna: boolean | null;
  enable_reviews: boolean | null;
  enable_certificates: boolean | null;
  drip_schedule: Record<string, unknown> | null;
  completion_criteria: Record<string, unknown> | null;
};